# BEA API

Testing the API from the Bureau of Economic Analysis.  
API documentation [here](https://apps.bea.gov/API/bea_web_service_api_user_guide.htm)

In [1]:
import pandas as pd
import requests
import os

# path for the folder "project"
path = "C:\\Users\\pedro\\OneDrive\\NYU\\CSS\\II. Data Skills\\project"
os.chdir(path)

import keys # file with api keys
key = keys.BEA

Getting all available tables:

In [2]:
main = "https://apps.bea.gov/api/data/?&UserID={}".format(key)
method = "&method=GETDATASETLIST"

In [3]:
# Request parameter information from BEA API
url = "{}{}&ResultFormat=JSON".format(main,method)
r = requests.get(url).json()

In [4]:
pd.DataFrame(r['BEAAPI']['Results']['Dataset'])

                DatasetName                    DatasetDescription
0                      NIPA                  Standard NIPA tables
1        NIUnderlyingDetail  Standard NI underlying detail tables
2                       MNE             Multinational Enterprises
3               FixedAssets          Standard Fixed Assets tables
4                       ITA   International Transactions Accounts
5                       IIP     International Investment Position
6               InputOutput                     Input-Output Data
7             IntlServTrade          International Services Trade
8             GDPbyIndustry                       GDP by Industry
9                  Regional                    Regional data sets
10  UnderlyingGDPbyIndustry            Underlying GDP by Industry
11       APIDatasetMetaData     Metadata about other API datasets

Lets get the "NIPA" data (National Income and Product Accounts)

In [5]:
# Components of request
main = "https://apps.bea.gov/api/data/?&UserID={}".format(key)
method = '&method=GetParameterValues'
dataset = '&DataSetName=NIPA'
param = 'TableName'

In [6]:
# Construct URL from parameters above
url = '{}{}{}&ParameterName={}&ResultFormat=json'.format(main, method, dataset, param)

# Request parameter information from BEA API
r = requests.get(url).json()

with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'max_colwidth', -1, 'display.expand_frame_repr', False):
    print (pd.DataFrame(r['BEAAPI']['Results']['ParamValue']))

# Relevant Tables:
# GDP
# T10102 Table 1.1.2. Contributions to Percent Change in Real Gross Domestic Product (A) (Q)
# T10103 Table 1.1.3. Real Gross Domestic Product, Quantity Indexes (A) (Q)
# T10106 Table 1.1.6. Real Gross Domestic Product, Chained Dollars (A) (Q)
# T10503 Table 1.5.3. Real Gross Domestic Product, Expanded Detail, Quantity Indexes (A) (Q)
# T10506 Table 1.5.6. Real Gross Domestic Product, Expanded Detail, Chained Dollars (A) (Q)

#T80103    Table 8.1.3. Real Gross Domestic Product, Quantity Indexes, Not Seasonally Adjusted (Q)                                                                                                        
#T80106    Table 8.1.6. Real Gross Domestic Product, Chained Dollars, Not Seasonally Adjusted (Q)

# PCE (Q)
#T20302 Table 2.3.2. Contributions to Percent Change in Real Personal Consumption Expenditures by Major Type of Product (A) (Q)
#T20303 Table 2.3.3. Real Personal Consumption Expenditures by Major Type of Product, Quantity Indexes (A) (Q)                                                                                         
#T20304 Table 2.3.4. Price Indexes for Personal Consumption Expenditures by Major Type of Product (A) (Q)                                                                                              
#T20306 Table 2.3.6. Real Personal Consumption Expenditures by Major Type of Product, Chained Dollars (A) (Q)

# PCE (M)
#T20803 Table 2.8.3. Real Personal Consumption Expenditures by Major Type of Product, Monthly, Quantity Indexes (M)                                                                                    
#T20804 Table 2.8.4. Price Indexes for Personal Consumption Expenditures by Major Type of Product, Monthly (M)                                                                                         
#T20806 Table 2.8.6. Real Personal Consumption Expenditures by Major Type of Product, Monthly, Chained Dollars (M)

# Government
#T30902 Table 3.9.2. Contributions to Percent Change in Real Government Consumption Expenditures and Gross Investment (A) (Q)
#T30903 Table 3.9.3. Real Government Consumption Expenditures and Gross Investment, Quantity Indexes (A) (Q)                                                                                           
#T30906 Table 3.9.6. Real Government Consumption Expenditures and Gross Investment, Chained Dollars (A) (Q)

# Exports and Imports
#T40100 Table 4.1. Foreign Transactions in the National Income and Product Accounts (A) (Q)                                                                                                            
#T40202 Table 4.2.2. Contributions to Percent Change in Real Exports and Real Imports of Goods and Services by Type of Product (A) (Q)
#T40203 Table 4.2.3. Real Exports and Imports of Goods and Services by Type of Product, Quantity Indexes (A) (Q)                                                                                       
#T40206 Table 4.2.6. Real Exports and Imports of Goods and Services by Type of Product, Chained Dollars (A) (Q)

# Investments
#T50100 Table 5.1. Saving and Investment by Sector (A) (Q)
#T50302 Table 5.3.2. Contributions to Percent Change in Real Private Fixed Investment by Type (A) (Q)                                                                                                  
#T50303 Table 5.3.3. Real Private Fixed Investment by Type, Quantity Indexes (A) (Q)                                                                                                                   
#T50306 Table 5.3.6. Real Private Fixed Investment by Type, Chained Dollars (A) (Q)

# Inventories
#T50706A Table 5.7.6A. Change in Real Private Inventories by Industry, Chained Dollars (A) (Q)                                                                                                          
#T50706B Table 5.7.6B. Change in Real Private Inventories by Industry, Chained Dollars (A) (Q)

#T50806A Table 5.8.6A. Real Private Inventories and Real Domestic Final Sales of Business by Industry, Chained Dollars (Q)                                                                              
#T50806B Table 5.8.6B. Real Private Inventories and Real Domestic Final Sales by Industry, Chained Dollars (Q)

# Personal Income
# T20600 Table 2.6. Personal Income and Its Disposition, Monthly (M)

    TableName                                                                                                                                                                                      Description
0    T10101    Table 1.1.1. Percent Change From Preceding Period in Real Gross Domestic Product (A) (Q)
1    T10102    Table 1.1.2. Contributions to Percent Change in Real Gross Domestic Product (A) (Q)
2    T10103    Table 1.1.3. Real Gross Domestic Product, Quantity Indexes (A) (Q)
3    T10104    Table 1.1.4. Price Indexes for Gross Domestic Product (A) (Q)
4    T10105    Table 1.1.5. Gross Domestic Product (A) (Q)
5    T10106    Table 1.1.6. Real Gross Domestic Product, Chained Dollars (A) (Q)
6    T10107    Table 1.1.7. Percent Change From Preceding Period in Prices for Gross Domestic Product (A) (Q)
7    T10108    Table 1.1.8. Contributions to Percent Change in the Gross Domestic Product Price Index (A) (Q)
8    T10109    Table 1.1.9. Implicit Price Deflators for Gross Domestic Product (A) (Q)
9    T10110    Table 1.1.10. Percentage Shares of Gross Domestic Product (A) (Q)
10   T10111    Table 1.1.11. Real Gross Domestic Product: Percent Change From Quarter One Year Ago (Q)
11   T10201    Table 1.2.1. Percent Change From Preceding Period in Real Gross Domestic Product by Major Type of Product (A) (Q)
12   T10202    Table 1.2.2. Contributions to Percent Change in Real Gross Domestic Product by Major Type of Product (A) (Q)
13   T10203    Table 1.2.3. Real Gross Domestic Product by Major Type of Product, Quantity Indexes (A) (Q)
14   T10204    Table 1.2.4. Price Indexes for Gross Domestic Product by Major Type of Product (A) (Q)
15   T10205    Table 1.2.5. Gross Domestic Product by Major Type of Product (A) (Q)
16   T10206    Table 1.2.6. Real Gross Domestic Product by Major Type of Product, Chained Dollars (A) (Q)
17   T10301    Table 1.3.1. Percent Change From Preceding Period in Real Gross Value Added by Sector (A) (Q)
18   T10303    Table 1.3.3. Real Gross Value Added by Sector, Quantity Indexes (A) (Q)
19   T10304    Table 1.3.4. Price Indexes for Gross Value Added by Sector (A) (Q)
20   T10305    Table 1.3.5. Gross Value Added by Sector (A) (Q)
21   T10306    Table 1.3.6. Real Gross Value Added by Sector, Chained Dollars (A) (Q)
22   T10401    Table 1.4.1. Percent Change From Preceding Period in Real Gross Domestic Product, Real Gross Domestic Purchases, and Real Final Sales to Domestic Purchasers (A) (Q)
23   T10403    Table 1.4.3. Real Gross Domestic Product, Real Gross Domestic Purchases, and Real Final Sales to Domestic Purchasers, Quantity Indexes (A) (Q)
24   T10404    Table 1.4.4. Price Indexes for Gross Domestic Product, Gross Domestic Purchases, and Final Sales to Domestic Purchasers (A) (Q)
25   T10405    Table 1.4.5. Relation of Gross Domestic Product, Gross Domestic Purchases, and Final Sales to Domestic Purchasers (A) (Q)
26   T10406    Table 1.4.6. Relation of Real Gross Domestic Product, Real Gross Domestic Purchases, and Real Final Sales to Domestic Purchasers, Chained Dollars (A) (Q)
27   T10501    Table 1.5.1. Percent Change From Preceding Period in Real Gross Domestic Product, Expanded Detail (A) (Q)
28   T10502    Table 1.5.2. Contributions to Percent Change in Real Gross Domestic Product, Expanded Detail (A) (Q)
29   T10503    Table 1.5.3. Real Gross Domestic Product, Expanded Detail, Quantity Indexes (A) (Q)
30   T10504    Table 1.5.4. Price Indexes for Gross Domestic Product, Expanded Detail (A) (Q)
31   T10505    Table 1.5.5. Gross Domestic Product, Expanded Detail (A) (Q)
32   T10506    Table 1.5.6. Real Gross Domestic Product, Expanded Detail, Chained Dollars (A) (Q)
33   T10604    Table 1.6.4. Price Indexes for Gross Domestic Purchases (A) (Q)
34   T10607    Table 1.6.7. Percent Change From Preceding Period in Prices for Gross Domestic Purchases (A) (Q)
35   T10608    Table 1.6.8. Contributions to Percent Change in the Gross Domestic Purchases Price Index (A) (Q)
36   T10701    Table 1.7.1. Percent Change From Preceding Period in Real Gross Domestic Product, Real Gross National Product, and Real Net National Product (A) (Q)
37   T10703    Table 1.7.3. Real Gross Domestic Product, Real Gross National Product, and Real Net National Product, Quantity Indexes (A) (Q)
38   T10704    Table 1.7.4. Price Indexes for Gross Domestic Product, Gross National Product, and Net National Product (A) (Q)
39   T10705    Table 1.7.5. Relation of Gross Domestic Product, Gross National Product, Net National Product, National Income, and Personal Income (A) (Q)
40   T10706    Table 1.7.6. Relation of Real Gross Domestic Product, Real Gross National Product, and Real Net National Product, Chained Dollars (A) (Q)
41   T10803    Table 1.8.3. Command-Basis Real Gross Domestic Product and Gross National Product, Quantity Indexes (A) (Q)
42   T10806    Table 1.8.6. Command-Basis Real Gross Domestic Product and Gross National Product, Chained Dollars (A) (Q)
43   T10903    Table 1.9.3. Real Net Value Added by Sector, Quantity Indexes (A)
44   T10904    Table 1.9.4. Price Indexes for Net Value Added by Sector (A)
45   T10905    Table 1.9.5. Net Value Added by Sector (A)
46   T10906    Table 1.9.6. Real Net Value Added by Sector, Chained Dollars (A)
47   T11000    Table 1.10. Gross Domestic Income by Type of Income (A) (Q)
48   T11100    Table 1.11. Percentage Shares of Gross Domestic Income (A)
49   T11200    Table 1.12. National Income by Type of Income (A) (Q)
50   T11300    Table 1.13. National Income by Sector, Legal Form of Organization, and Type of Income (A)
51   T11400    Table 1.14. Gross Value Added of Domestic Corporate Business in Current Dollars and Gross Value Added of Nonfinancial Domestic Corporate Business in Current and Chained Dollars (A) (Q)
52   T11500    Table 1.15. Price, Costs, and Profit Per Unit of Real Gross Value Added of Nonfinancial Domestic Corporate Business (A) (Q)
53   T11600    Table 1.16. Sources and Uses of Private Enterprise Income (A)
54   T11701    Table 1.17.1. Percent Change From Preceding Period in Real Gross Domestic Product, Real Gross Domestic Income, and Other Major NIPA Aggregates (A) (Q)
55   T11705    Table 1.17.5. Gross Domestic Product, Gross Domestic Income, and Other Major NIPA Aggregates (A) (Q)
56   T11706    Table 1.17.6. Real Gross Domestic Product, Real Gross Domestic Income, and Other Major NIPA Aggregates, Chained Dollars (A) (Q)
57   T20100    Table 2.1. Personal Income and Its Disposition (A) (Q)
58   T20200A   Table 2.2A. Wages and Salaries by Industry (A) (Q)
59   T20200B   Table 2.2B. Wages and Salaries by Industry (A) (Q)
60   T20301    Table 2.3.1. Percent Change From Preceding Period in Real Personal Consumption Expenditures by Major Type of Product (A) (Q)
61   T20302    Table 2.3.2. Contributions to Percent Change in Real Personal Consumption Expenditures by Major Type of Product (A) (Q)
62   T20303    Table 2.3.3. Real Personal Consumption Expenditures by Major Type of Product, Quantity Indexes (A) (Q)
63   T20304    Table 2.3.4. Price Indexes for Personal Consumption Expenditures by Major Type of Product (A) (Q)
64   T20305    Table 2.3.5. Personal Consumption Expenditures by Major Type of Product (A) (Q)
65   T20306    Table 2.3.6. Real Personal Consumption Expenditures by Major Type of Product, Chained Dollars (A) (Q)
66   T20307    Table 2.3.7. Percent Change From Preceding Period in Prices for Personal Consumption Expenditures by Major Type of Product (A) (Q)
67   T20403    Table 2.4.3. Real Personal Consumption Expenditures by Type of Product, Quantity Indexes (A)
68   T20404    Table 2.4.4. Price Indexes for Personal Consumption Expenditures by Type of Product (A)
69   T20405    Table 2.4.5. Personal Consumption Expenditures by Type of Product (A)
70   T20406    Table 2.4.6. Real Personal Consumption Expenditures by Type of Product, Chained Dollars (A)
71   T20503    Table 2.5.3. Real Personal Consumption Expenditures by Function, Quantity Indexes (A)
72   T20504    Table 2.5.4. Price Indexes for Personal Consumption Expenditures by Function (A)
73   T20505    Table 2.5.5. Personal Consumption Expenditures by Function (A)
74   T20506    Table 2.5.6. Real Personal Consumption Expenditures by Function, Chained Dollars (A)
75   T20600    Table 2.6. Personal Income and Its Disposition, Monthly (M)
76   T20700A   Table 2.7A. Wages and Salaries by Industry, Monthly (M)
77   T20700B   Table 2.7B. Wages and Salaries by Industry, Monthly (M)
78   T20801    Table 2.8.1. Percent Change From Preceding Period in Real Personal Consumption Expenditures by Major Type of Product, Monthly (M)
79   T20803    Table 2.8.3. Real Personal Consumption Expenditures by Major Type of Product, Monthly, Quantity Indexes (M)
80   T20804    Table 2.8.4. Price Indexes for Personal Consumption Expenditures by Major Type of Product, Monthly (M)
81   T20805    Table 2.8.5. Personal Consumption Expenditures by Major Type of Product, Monthly (M)
82   T20806    Table 2.8.6. Real Personal Consumption Expenditures by Major Type of Product, Monthly, Chained Dollars (M)
83   T20807    Table 2.8.7. Percent Change From Preceding Period in Prices for Personal Consumption Expenditures by Major Type of Product, Monthly (M)
84   T20900    Table 2.9. Personal Income and Its Disposition by Households and by Nonprofit Institutions Serving Households (A)
85   T30100    Table 3.1. Government Current Receipts and Expenditures (A) (Q)
86   T30200    Table 3.2. Federal Government Current Receipts and Expenditures (A) (Q)
87   T30300    Table 3.3. State and Local Government Current Receipts and Expenditures (A) (Q)
88   T30400    Table 3.4. Personal Current Tax Receipts (A)
89   T30500    Table 3.5. Taxes on Production and Imports (A)
90   T30600    Table 3.6. Contributions for Government Social Insurance (A)
91   T30700    Table 3.7. Government Current Transfer Receipts (A)
92   T30800    Table 3.8. Current Surplus of Government Enterprises (A)
93   T30901    Table 3.9.1. Percent Change From Preceding Period in Real Government Consumption Expenditures and Gross Investment (A) (Q)
94   T30902    Table 3.9.2. Contributions to Percent Change in Real Government Consumption Expenditures and Gross Investment (A) (Q)
95   T30903    Table 3.9.3. Real Government Consumption Expenditures and Gross Investment, Quantity Indexes (A) (Q)
96   T30904    Table 3.9.4. Price Indexes for Government Consumption Expenditures and Gross Investment (A) (Q)
97   T30905    Table 3.9.5. Government Consumption Expenditures and Gross Investment (A) (Q)
98   T30906    Table 3.9.6. Real Government Consumption Expenditures and Gross Investment, Chained Dollars (A) (Q)
99   T31001    Table 3.10.1. Percent Change From Preceding Period in Real Government Consumption Expenditures and General Government Gross Output (A) (Q)
100  T31003    Table 3.10.3. Real Government Consumption Expenditures and General Government Gross Output, Quantity Indexes (A) (Q)
101  T31004    Table 3.10.4. Price Indexes for Government Consumption Expenditures and General Government Gross Output (A) (Q)
102  T31005    Table 3.10.5. Government Consumption Expenditures and General Government Gross Output (A) (Q)
103  T31006    Table 3.10.6. Real Government Consumption Expenditures and General Government Gross Output, Chained Dollars (A) (Q)
104  T31101    Table 3.11.1. Percent Change From Preceding Period in Real National Defense Consumption Expenditures and Gross Investment by Type (A) (Q)
105  T31102    Table 3.11.2. Contributions to Percent Change in National Defense Consumption Expenditures and Gross Investment by Type (A) (Q)
106  T31103    Table 3.11.3. Real National Defense Consumption Expenditures and Gross Investment by Type, Quantity Indexes (A) (Q)
107  T31104    Table 3.11.4. Price Indexes for National Defense Consumption Expenditures and Gross Investment by Type (A) (Q)
108  T31105    Table 3.11.5. National Defense Consumption Expenditures and Gross Investment by Type (A) (Q)
109  T31106    Table 3.11.6. Real National Defense Consumption Expenditures and Gross Investment by Type, Chained Dollars (A) (Q)
110  T31200    Table 3.12. Government Social Benefits (A)
111  T31300    Table 3.13. Subsidies (A)
112  T31400    Table 3.14. Government Social Insurance Funds Current Receipts and Expenditures (A)
113  T31501    Table 3.15.1. Percent Change From Preceding Period in Real Government Consumption Expenditures and Gross Investment by Function (A)
114  T31502    Table 3.15.2. Contributions to Percent Change in Real Government Consumption Expenditures and Gross Investment by Function (A)
115  T31503    Table 3.15.3. Real Government Consumption Expenditures and Gross Investment by Function, Quantity Indexes (A)
116  T31504    Table 3.15.4. Price Indexes for Government Consumption Expenditures and Gross Investment by Function (A)
117  T31505    Table 3.15.5. Government Consumption Expenditures and Gross Investment by Function (A)
118  T31506    Table 3.15.6. Real Government Consumption Expenditures and Gross Investment by Function, Chained Dollars (A)
119  T31600    Table 3.16. Government Current Expenditures by Function (A)
120  T31700    Table 3.17. Selected Government Current and Capital Expenditures by Function (A)
121  T31800A   Table 3.18A. Relation of Federal Government Current Receipts and Expenditures in the National Income and Product Accounts to the Consolidated Cash Statement, Fiscal Years and Quarters (A) (Q)
122  T31800B   Table 3.18B. Relation of Federal Government Current Receipts and Expenditures in the National Income and Product Accounts to the Budget, Fiscal Years and Quarters (A) (Q)
123  T31900    Table 3.19. Relation of State and Local Government Current Receipts and Expenditures in the National Income and Product Accounts to Census Bureau 'Government Finances' Data, Fiscal Years (A)
124  T32000    Table 3.20. State Government Current Receipts and Expenditures (A)
125  T32100    Table 3.21. Local Government Current Receipts and Expenditures (A)
126  T40100    Table 4.1. Foreign Transactions in the National Income and Product Accounts (A) (Q)
127  T40201    Table 4.2.1. Percent Change From Preceding Period in Real Exports and in Real Imports of Goods and Services by Type of Product (A) (Q)
128  T40202    Table 4.2.2. Contributions to Percent Change in Real Exports and Real Imports of Goods and Services by Type of Product (A) (Q)
129  T40203    Table 4.2.3. Real Exports and Imports of Goods and Services by Type of Product, Quantity Indexes (A) (Q)
130  T40204    Table 4.2.4. Price Indexes for Exports and Imports of Goods and Services by Type of Product (A) (Q)
131  T40205    Table 4.2.5. Exports and Imports of Goods and Services by Type of Product (A) (Q)
132  T40206    Table 4.2.6. Real Exports and Imports of Goods and Services by Type of Product, Chained Dollars (A) (Q)
133  T4030A    Table 4.3A. Relation of Foreign Transactions in the National Income and Product Accounts to the Corresponding Items in the International Transactions Accounts (A)
134  T4030B    Table 4.3B. Relation of Foreign Transactions in the National Income and Product Accounts to the Corresponding Items in the International Transactions Accounts (A)
135  T4030C    Table 4.3C. Relation of Foreign Transactions in the National Income and Product Accounts to the Corresponding Items in the International Transactions Accounts (A) (Q)
136  T50100    Table 5.1. Saving and Investment by Sector (A) (Q)
137  T50203    Table 5.2.3. Real Gross and Net Domestic Investment by Major Type, Quantity Indexes (A)
138  T50205    Table 5.2.5. Gross and Net Domestic Investment by Major Type (A)
139  T50206    Table 5.2.6. Real Gross and Net Domestic Investment by Major Type, Chained dollars (A)
140  T50301    Table 5.3.1. Percent Change From Preceding Period in Real Private Fixed Investment by Type (A) (Q)
141  T50302    Table 5.3.2. Contributions to Percent Change in Real Private Fixed Investment by Type (A) (Q)
142  T50303    Table 5.3.3. Real Private Fixed Investment by Type, Quantity Indexes (A) (Q)
143  T50304    Table 5.3.4. Price Indexes for Private Fixed Investment by Type (A) (Q)
144  T50305    Table 5.3.5. Private Fixed Investment by Type (A) (Q)
145  T50306    Table 5.3.6. Real Private Fixed Investment by Type, Chained Dollars (A) (Q)
146  T50401    Table 5.4.1. Percent Change From Preceding Period in Real Private Fixed Investment in Structures by Type (A)
147  T50402    Table 5.4.2. Contributions to Percent Change in Real Private Fixed Investment in Structures by Type (A)
148  T50403    Table 5.4.3. Real Private Fixed Investment in Structures by Type, Quantity Indexes (A)
149  T50404    Table 5.4.4. Price Indexes for Private Fixed Investment in Structures by Type (A)
150  T50405    Table 5.4.5. Private Fixed Investment in Structures by Type (A)
151  T50406    Table 5.4.6. Real Private Fixed Investment in Structures by Type, Chained Dollars (A)
152  T50501    Table 5.5.1. Percent Change From Preceding Period in Real Private Fixed Investment in Equipment by Type (A)
153  T50502    Table 5.5.2. Contributions to Percent Change in Real Private Fixed Investment in Equipment by Type (A)
154  T50503    Table 5.5.3. Real Private Fixed Investment in Equipment by Type, Quantity Indexes (A)
155  T50504    Table 5.5.4. Price Indexes for Private Fixed Investment in Equipment by Type (A)
156  T50505    Table 5.5.5. Private Fixed Investment in Equipment by Type (A)
157  T50506    Table 5.5.6. Real Private Fixed Investment in Equipment by Type, Chained Dollars (A)
158  T50601    Table 5.6.1. Percent Change From Preceding Period in Real Private Fixed Investment in Intellectual Property Products by Type (A)
159  T50602    Table 5.6.2. Contributions to Percent Change in Private Fixed Investment in Intellectual Property Products by Type (A)
160  T50603    Table 5.6.3. Real Private Fixed Investment in Intellectual Property Products by Type, Quantity Indexes (A)
161  T50604    Table 5.6.4. Price Indexes for Private Fixed Investment in Intellectual Property Products by Type (A)
162  T50605    Table 5.6.5. Private Fixed Investment in Intellectual Property Products by Type (A)
163  T50606    Table 5.6.6. Real Private Fixed Investment in Intellectual Property Products by Type, Chained Dollars (A)
164  T50705A   Table 5.7.5A. Change in Private Inventories by Industry (A) (Q)
165  T50705B   Table 5.7.5B. Change in Private Inventories by Industry (A) (Q)
166  T50706A   Table 5.7.6A. Change in Real Private Inventories by Industry, Chained Dollars (A) (Q)
167  T50706B   Table 5.7.6B. Change in Real Private Inventories by Industry, Chained Dollars (A) (Q)
168  T50805A   Table 5.8.5A. Private Inventories and Domestic Final Sales of Business by Industry (Q)
169  T50805B   Table 5.8.5B. Private Inventories and Domestic Final Sales by Industry (Q)
170  T50806A   Table 5.8.6A. Real Private Inventories and Real Domestic Final Sales of Business by Industry, Chained Dollars (Q)
171  T50806B   Table 5.8.6B. Real Private Inventories and Real Domestic Final Sales by Industry, Chained Dollars (Q)
172  T50809A   Table 5.8.9A. Implicit Price Deflators for Private Inventories by Industry (Q)
173  T50809B   Table 5.8.9B. Implicit Price Deflators for Private Inventories by Industry (Q)
174  T50903    Table 5.9.3. Real Gross Government Fixed Investment by Type, Quantity Indexes (A)
175  T50904    Table 5.9.4. Price Indexes for Gross Government Fixed Investment by Type (A)
176  T50905    Table 5.9.5. Gross Government Fixed Investment by Type (A)
177  T50906    Table 5.9.6. Real Gross Government Fixed Investment by Type, Chained Dollars (A)
178  T51000    Table 5.10. Changes in Net Stock of Produced Assets (Fixed Assets and Inventories) (A)
179  T51100    Table 5.11. Capital Transfers Paid and Received, by Sector and by Type (A)
180  T60100B   Table 6.1B. National Income Without Capital Consumption Adjustment by Industry (A) (Q)

## Function to GET NIPA data

In [7]:
def get_bea_nipa(key, table, frequency, year = "ALL", fmt = "json"):
    """
    Description: GET request for NIPA tables from BEA.
    ---
    Paramns:
        table [str]: NIPA Table Name.
        frequency [str]: Monthly (M), Quarterly (Q) or Annual (A) data.
        year [str]: Periods. Default is data for all years.
        fmt [str]: Format of the response. Default is json.
        key [str]: Individual BEA API Key.
    ---
    Returns: Pandas DataFrame with the NIPA table.
    """
    
    main = "https://apps.bea.gov/api/data/?&UserID={}".format(key)
    method = "&method=GetData"
    dataset = '&DataSetName=NIPA'
    ind = '&TableName={}'.format(table)
    freq = '&Frequency={}'.format(frequency)
    year = '&Year={}'.format(year)
    fmt = '&ResultFormat={}'.format(fmt)

    # Combined url for request
    url = '{}{}{}{}{}{}{}'.format(main, method, dataset, year, ind, freq, fmt)
    r = requests.get(url).json()

    return pd.DataFrame(r['BEAAPI']['Results']['Data'])

## GDP

In [8]:
# Table 1.1.3. Real Gross Domestic Product, Quantity Indexes (A) (Q)
gdp_quantity = get_bea_nipa(key = key, table = "T10103", frequency = "Q")

In [9]:
gdp_quantity.head()

,TableName,SeriesCode,LineNumber,LineDescription,TimePeriod,METRIC_NAME,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,T10103,A191RA,1,Gross domestic product,1947Q1,Fisher Quantity Index,Level,0,12.517,T10103
1,T10103,A191RA,1,Gross domestic product,1947Q2,Fisher Quantity Index,Level,0,12.483,T10103
2,T10103,A191RA,1,Gross domestic product,1947Q3,Fisher Quantity Index,Level,0,12.457,T10103
3,T10103,A191RA,1,Gross domestic product,1947Q4,Fisher Quantity Index,Level,0,12.652,T10103
4,T10103,A191RA,1,Gross domestic product,1948Q1,Fisher Quantity Index,Level,0,12.843,T10103

In [10]:
#T10102 Table 1.1.2. Contributions to Percent Change in Real Gross Domestic Product (A) (Q)
gdp_contribution = get_bea_nipa(key = key, table = "T10102", frequency = "Q")

In [11]:
gdp_contribution.head()

,TableName,SeriesCode,LineNumber,LineDescription,TimePeriod,METRIC_NAME,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,T10102,A191RL,1,Gross domestic product,1947Q2,Fisher Quantity Index,"Percent change, annual rate",0,-1.1,T10102
1,T10102,A191RL,1,Gross domestic product,1947Q3,Fisher Quantity Index,"Percent change, annual rate",0,-0.8,T10102
2,T10102,A191RL,1,Gross domestic product,1947Q4,Fisher Quantity Index,"Percent change, annual rate",0,6.4,T10102
3,T10102,A191RL,1,Gross domestic product,1948Q1,Fisher Quantity Index,"Percent change, annual rate",0,6.2,T10102
4,T10102,A191RL,1,Gross domestic product,1948Q2,Fisher Quantity Index,"Percent change, annual rate",0,6.8,T10102

In [12]:
# T10106 Table 1.1.6. Real Gross Domestic Product, Chained Dollars (A) (Q)
gdp_dollars = get_bea_nipa(key = key, table = "T10106", frequency = "Q")

In [13]:
gdp_dollars.head()

,TableName,SeriesCode,LineNumber,LineDescription,TimePeriod,METRIC_NAME,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,T10106,A191RX,1,Gross domestic product,1947Q1,Chained Dollars,Level,6,"2,034,450",T10106
1,T10106,A191RX,1,Gross domestic product,1947Q2,Chained Dollars,Level,6,"2,029,024",T10106
2,T10106,A191RX,1,Gross domestic product,1947Q3,Chained Dollars,Level,6,"2,024,834",T10106
3,T10106,A191RX,1,Gross domestic product,1947Q4,Chained Dollars,Level,6,"2,056,508",T10106
4,T10106,A191RX,1,Gross domestic product,1948Q1,Chained Dollars,Level,6,"2,087,442",T10106

In [14]:
gdp = pd.concat([gdp_quantity, gdp_dollars, gdp_contribution])
gdp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19765 entries, 0 to 7851
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TableName        19765 non-null  object
 1   SeriesCode       19765 non-null  object
 2   LineNumber       19765 non-null  object
 3   LineDescription  19765 non-null  object
 4   TimePeriod       19765 non-null  object
 5   METRIC_NAME      19765 non-null  object
 6   CL_UNIT          19765 non-null  object
 7   UNIT_MULT        19765 non-null  object
 8   DataValue        19765 non-null  object
 9   NoteRef          19765 non-null  object
dtypes: object(10)
memory usage: 1.7+ MB

In [15]:
# changing columns dtypes:
gdp["TimePeriod"]= gdp["TimePeriod"].str.replace("Q4", "-12-01", regex=False)
gdp["TimePeriod"]= gdp["TimePeriod"].str.replace("Q3", "-09-01", regex=False)
gdp["TimePeriod"]= gdp["TimePeriod"].str.replace("Q2", "-06-01", regex=False)
gdp["TimePeriod"]= gdp["TimePeriod"].str.replace("Q1", "-03-01", regex=False)
gdp["TimePeriod"]= pd.to_datetime(gdp["TimePeriod"])

gdp["DataValue"]= pd.to_numeric(gdp["DataValue"].str.replace(",", "", regex=False))

# creating series id
gdp["series_id"] = gdp["TableName"] + "_" + gdp["SeriesCode"]

In [16]:
gdp.head()

,TableName,SeriesCode,LineNumber,LineDescription,TimePeriod,METRIC_NAME,CL_UNIT,UNIT_MULT,DataValue,NoteRef,series_id
0,T10103,A191RA,1,Gross domestic product,1947-03-01,Fisher Quantity Index,Level,0,12.517,T10103,T10103_A191RA
1,T10103,A191RA,1,Gross domestic product,1947-06-01,Fisher Quantity Index,Level,0,12.483,T10103,T10103_A191RA
2,T10103,A191RA,1,Gross domestic product,1947-09-01,Fisher Quantity Index,Level,0,12.457,T10103,T10103_A191RA
3,T10103,A191RA,1,Gross domestic product,1947-12-01,Fisher Quantity Index,Level,0,12.652,T10103,T10103_A191RA
4,T10103,A191RA,1,Gross domestic product,1948-03-01,Fisher Quantity Index,Level,0,12.843,T10103,T10103_A191RA

In [17]:
# dropping and renaming columns:
gdp = (
    gdp[["series_id","TimePeriod","DataValue","LineDescription","METRIC_NAME","CL_UNIT"]]
    .rename(columns = {"DataValue":"value", "TimePeriod":"date"}))

gdp.head()

,series_id,date,value,LineDescription,METRIC_NAME,CL_UNIT
0,T10103_A191RA,1947-03-01,12.517,Gross domestic product,Fisher Quantity Index,Level
1,T10103_A191RA,1947-06-01,12.483,Gross domestic product,Fisher Quantity Index,Level
2,T10103_A191RA,1947-09-01,12.457,Gross domestic product,Fisher Quantity Index,Level
3,T10103_A191RA,1947-12-01,12.652,Gross domestic product,Fisher Quantity Index,Level
4,T10103_A191RA,1948-03-01,12.843,Gross domestic product,Fisher Quantity Index,Level

In [18]:
gdp.to_parquet("data\\activity\\data_bea_gdp.parquet")

# PCE

In [19]:
#T20803 Table 2.8.3. Real Personal Consumption Expenditures by Major Type of Product, Monthly, Quantity Indexes (M)                                                                                                                                                                         
#T20806 Table 2.8.6. Real Personal Consumption Expenditures by Major Type of Product, Monthly, Chained Dollars (M)

pce_quantity = get_bea_nipa(key = key, table = "T20803", frequency = "M")
pce_dollars = get_bea_nipa(key = key, table = "T20806", frequency = "M")

pce = pd.concat([pce_quantity,pce_dollars])
pce.head()

,TableName,SeriesCode,LineNumber,LineDescription,TimePeriod,METRIC_NAME,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,T20803,DPCERA,1,Personal consumption expenditures (PCE),1959M01,Fisher Quantity Index,Level,0,17.272,T20803
1,T20803,DPCERA,1,Personal consumption expenditures (PCE),1959M02,Fisher Quantity Index,Level,0,17.452,T20803
2,T20803,DPCERA,1,Personal consumption expenditures (PCE),1959M03,Fisher Quantity Index,Level,0,17.617,T20803
3,T20803,DPCERA,1,Personal consumption expenditures (PCE),1959M04,Fisher Quantity Index,Level,0,17.553,T20803
4,T20803,DPCERA,1,Personal consumption expenditures (PCE),1959M05,Fisher Quantity Index,Level,0,17.765,T20803

In [20]:
# changing columns dtypes:
pce["TimePeriod"]= pce["TimePeriod"].str.replace("M", "-", regex=False)
pce["TimePeriod"]= pd.to_datetime(pce["TimePeriod"]+"-01")

pce["DataValue"]= pd.to_numeric(pce["DataValue"].str.replace(",", "", regex=False))

# creating series id
pce["series_id"] = pce["TableName"] + "_" + pce["SeriesCode"]

In [21]:
# dropping and renaming columns:
pce = (
    pce[["series_id","TimePeriod","DataValue","LineDescription","METRIC_NAME","CL_UNIT"]]
    .rename(columns = {"DataValue":"value", "TimePeriod":"date"}))

pce.head()

,series_id,date,value,LineDescription,METRIC_NAME,CL_UNIT
0,T20803_DPCERA,1959-01-01,17.272,Personal consumption expenditures (PCE),Fisher Quantity Index,Level
1,T20803_DPCERA,1959-02-01,17.452,Personal consumption expenditures (PCE),Fisher Quantity Index,Level
2,T20803_DPCERA,1959-03-01,17.617,Personal consumption expenditures (PCE),Fisher Quantity Index,Level
3,T20803_DPCERA,1959-04-01,17.553,Personal consumption expenditures (PCE),Fisher Quantity Index,Level
4,T20803_DPCERA,1959-05-01,17.765,Personal consumption expenditures (PCE),Fisher Quantity Index,Level

In [22]:
pce.to_parquet("data\\activity\\data_bea_pce.parquet")

In [23]:
#T20804 Table 2.8.4. Price Indexes for Personal Consumption Expenditures by Major Type of Product, Monthly (M)
pce_inflation = get_bea_nipa(key = key, table = "T20804", frequency = "M")
pce_inflation.head()

,TableName,SeriesCode,LineNumber,LineDescription,TimePeriod,METRIC_NAME,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,T20804,DPCERG,1,Personal consumption expenditures (PCE),1959M01,Fisher Price Index,Level,0,16.042,T20804
1,T20804,DPCERG,1,Personal consumption expenditures (PCE),1959M02,Fisher Price Index,Level,0,16.057,T20804
2,T20804,DPCERG,1,Personal consumption expenditures (PCE),1959M03,Fisher Price Index,Level,0,16.068,T20804
3,T20804,DPCERG,1,Personal consumption expenditures (PCE),1959M04,Fisher Price Index,Level,0,16.100,T20804
4,T20804,DPCERG,1,Personal consumption expenditures (PCE),1959M05,Fisher Price Index,Level,0,16.109,T20804

In [24]:
# changing columns dtypes:
pce_inflation["TimePeriod"]= pce_inflation["TimePeriod"].str.replace("M", "-", regex=False)
pce_inflation["TimePeriod"]= pd.to_datetime(pce_inflation["TimePeriod"]+"-01")

pce_inflation["DataValue"]= pd.to_numeric(pce_inflation["DataValue"].str.replace(",", "", regex=False))

# creating series id
pce_inflation["series_id"] = pce_inflation["TableName"] + "_" + pce_inflation["SeriesCode"]

In [25]:
# dropping and renaming columns:
pce_inflation = (
    pce_inflation[["series_id","TimePeriod","DataValue","LineDescription","METRIC_NAME","CL_UNIT"]]
    .rename(columns = {"DataValue":"value", "TimePeriod":"date"}))

pce_inflation.head()

,series_id,date,value,LineDescription,METRIC_NAME,CL_UNIT
0,T20804_DPCERG,1959-01-01,16.042,Personal consumption expenditures (PCE),Fisher Price Index,Level
1,T20804_DPCERG,1959-02-01,16.057,Personal consumption expenditures (PCE),Fisher Price Index,Level
2,T20804_DPCERG,1959-03-01,16.068,Personal consumption expenditures (PCE),Fisher Price Index,Level
3,T20804_DPCERG,1959-04-01,16.100,Personal consumption expenditures (PCE),Fisher Price Index,Level
4,T20804_DPCERG,1959-05-01,16.109,Personal consumption expenditures (PCE),Fisher Price Index,Level

In [26]:
pce_inflation.to_parquet("data\\inflation\\data_bea_pce_inflation.parquet")

## Personal Income

In [27]:
# T20600 Table 2.6. Personal Income and Its Disposition, Monthly (M)
income = get_bea_nipa(key = key, table = "T20600", frequency = "M")
income.head()

,TableName,SeriesCode,LineNumber,LineDescription,TimePeriod,METRIC_NAME,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,T20600,A065RC,1,Personal income,1959M01,Current Dollars,Level,6,"391,771",T20600
1,T20600,A065RC,1,Personal income,1959M02,Current Dollars,Level,6,"393,682",T20600
2,T20600,A065RC,1,Personal income,1959M03,Current Dollars,Level,6,"396,493",T20600
3,T20600,A065RC,1,Personal income,1959M04,Current Dollars,Level,6,"399,871",T20600
4,T20600,A065RC,1,Personal income,1959M05,Current Dollars,Level,6,"402,407",T20600

In [28]:
# changing columns dtypes:
income["TimePeriod"]= income["TimePeriod"].str.replace("M", "-", regex=False)
income["TimePeriod"]= pd.to_datetime(income["TimePeriod"]+"-01")

income["DataValue"]= pd.to_numeric(income["DataValue"].str.replace(",", "", regex=False))

# creating series id
income["series_id"] = income["TableName"] + "_" + income["SeriesCode"]

In [29]:
# dropping and renaming columns:
income = (
    income[["series_id","TimePeriod","DataValue","LineDescription","METRIC_NAME","CL_UNIT"]]
    .rename(columns = {"DataValue":"value", "TimePeriod":"date"}))

income.head()

,series_id,date,value,LineDescription,METRIC_NAME,CL_UNIT
0,T20600_A065RC,1959-01-01,391771.0,Personal income,Current Dollars,Level
1,T20600_A065RC,1959-02-01,393682.0,Personal income,Current Dollars,Level
2,T20600_A065RC,1959-03-01,396493.0,Personal income,Current Dollars,Level
3,T20600_A065RC,1959-04-01,399871.0,Personal income,Current Dollars,Level
4,T20600_A065RC,1959-05-01,402407.0,Personal income,Current Dollars,Level

In [30]:
income.to_parquet("data\\activity\\data_bea_income.parquet")